### ISSUE TITLE
Stock not found

### ISSUE THREAD

**Issue by juancash** [HassaanAbbasi/Candlestick-Graphs#3]
Hi, thanks for your project.
I'm trying test the code, but when I search any stock always return 'Information for 'xxxxxxxx' does not exist'.

**Comment by HassaanAbbasi** [comment]
Hey Juan! Thanks for bringing this to my attention. I'd been busy with work recently so I only just now found the time to deal with this issue. I seem to have solved it by updating the required packages. Hope you find the project useful! :)
